TTAB-23_v2
Banyan-Labs/TTAB-backend pull request #6
Opened 2021-09-11 19:32 UTC by Joshua-Beets

sorry had some problems with the branch PR and the fact that i had that on already so i mode a version two and hope that you can just delete the old version and just use this one please let me know

2021-09-13 15:20 UTC, jmclain-banyan requested changes
[{
  "id": 1,
  "date": "9/13/2021",
  "startTime": "10:55 AM",
  "endTime": "10:28 AM"
}, {
  "id": 2,
  "date": "9/15/2021",
  "startTime": "12:50 PM",
  "endTime": "1:10 PM"
}, {
  "id": 3,
  "date": "9/14/2021",
  "startTime": "1:48 PM",
  "endTime": "2:28 PM"
}, {
  "id": 4,
  "date": "9/15/2021",
  "startTime": "11:25 AM",
  "endTime": "2:56 PM"
}, {
  "id": 5,
  "date": "9/13/2021",
  "startTime": "7:41 AM",
  "endTime": "1:44 PM"
}, {
  "id": 6,
  "date": "9/13/2021",
  "startTime": "8:03 AM",
  "endTime": "1:24 PM"
}, {
  "id": 7,
  "date": "9/14/2021",
  "startTime": "11:25 AM",
  "endTime": "10:05 AM"
}, {
  "id": 8,
  "date": "9/13/2021",
  "startTime": "9:41 AM",
  "endTime": "10:36 AM"
}, {
  "id": 9,
  "date": "9/15/2021",
  "startTime": "8:52 AM",
  "endTime": "11:59 AM"
}, {
  "id": 10,
  "date": "9/17/2021",
  "startTime": "1:28 PM",
  "endTime": "10:17 AM"
}, {
  "id": 11,
  "date": "9/13/2021",
  "startTime": "2:34 PM",
  "endTime": "9:06 AM"
}, {
  "id": 12,
  "date": "9/14/2021",
  "startTime": "12:06 PM",
  "endTime": "10:05 AM"
}, {
  "id": 13,
  "date": "9/17/2021",
  "startTime": "11:48 AM",
  "endTime": "10:26 AM"
}, {
  "id": 14,
  "date": "9/15/2021",
  "startTime": "7:58 AM",
  "endTime": "10:21 AM"
}, {
  "id": 15,
  "date": "9/14/2021",
  "startTime": "8:38 AM",
  "endTime": "7:30 AM"
}, {
  "id": 16,
  "date": "9/14/2021",
  "startTime": "7:56 AM",
  "endTime": "10:30 AM"
}, {
  "id": 17,
  "date": "9/13/2021",
  "startTime": "1:59 PM",
  "endTime": "8:21 AM"
}, {
  "id": 18,
  "date": "9/14/2021",
  "startTime": "11:36 AM",
  "endTime": "12:23 PM"
}, {
  "id": 19,
  "date": "9/17/2021",
  "startTime": "1:59 PM",
  "endTime": "2:39 PM"
}, {
  "id": 20,
  "date": "9/13/2021",
  "startTime": "7:46 AM",
  "endTime": "11:08 AM"
}]

2021-09-13 15:20 UTC, jmclain-banyan commented on routes/api/index.js
> +
we should be filtering using params in the URL of user id

2021-09-15 15:46 UTC, jmclain-banyan requested changes
Overall looks good😄 just need to resolve merge conflicts

2021-09-16 06:20 UTC, jmclain-banyan approved these changes

2021-09-16 06:20 UTC, merged

2021-09-16 06:55 UTC, Joshua-Beets commented
what


On Wed, Sep 15, 2021 at 11:21 PM Josh McLain ***@***.***>
wrote:

> Merged #6 <https://github.com/Banyan-Labs/TTAB-backend/pull/6> into dev.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Banyan-Labs/TTAB-backend/pull/6#event-5310269541>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUTNXHFVMYDIUNT2UICUPITUCGEFJANCNFSM5D3IJ6LA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>